In [45]:
import pandas as pd
import numpy as np

In [46]:
df = pd.read_csv('s3://datasetairbnb/airbnb_cleaned_winter.csv', encoding='Latin-1')

In [47]:
df['zipcode'] = pd.to_numeric(df['zipcode'], errors='coerce').fillna(0)
df['host_is_superhost'] = pd.to_numeric(df['host_is_superhost'], errors='coerce').fillna(0)

df

Unnamed: 0        id    host_id       scrape_id  zipcode  \
0                0      2515       2758  20181206022948  10026.0   
1                1     21456      42032  20181206022948  10025.0   
2                2      2539       2787  20181206022948  11218.0   
3                3      2595       2845  20181206022948  10018.0   
4                4     21644      82685  20181206022948  10031.0   
5                5      3330       4177  20181206022948  11206.0   
6                6     21794      83257  20181206022948  10014.0   
7                7      3647       4632  20181206022948  10027.0   
8                8     22911      87773  20181206022948  11233.0   
9                9     22918      32294  20181206022948  10031.0   
10              10      3831       4869  20181206022948  11238.0   
11              11     23135      11481  20181206022948  11231.0   
12              13     23180      90375  20181206022948  11205.0   
13              15      5099       7322  20181206022948  10016.0   
14              16     23545      92411  20181206022948  10031.0   
15              18      5178       8967  20181206022948  10019.0   
16              19     23686      93790  20181206022948  10014.0   
17              20      5203       7490  20181206022948  10025.0   
18              21     24143      97219  20181206022948  11206.0   
19              22     24285      97797  20181206022948  11215.0   
20              24     25235      87773  20181206022948  11233.0   
21              25      5238       7549  20181206022948  10002.0   
22              26     25406     105538  20181206022948  11211.0   
23              27      5295       7702  20181206022948  10025.0   
24              28      5441       7989  20181206022948  10036.0   
25              29     25696     107628  20181206022948  10027.0   
26              30      5586       8526  20181206022948  10065.0   
27              31     25915      25188  20181206022948  10019.0   
28              32      5803       9744  20181206022948  11215.0   
29              33     26012     109589  20181206022948  11217.0   
...            ...       ...        ...             ...      ...   
268606      275901  10115372   16740862  20170202135741  11237.0   
268607      275902  10115781   10221694  20170202135741  11249.0   
268608      275903   7887599   33451565  20170202135741  11206.0   
268609      275904  13658407   26929394  20170202135741  11211.0   
268610      275905   6973744   36566681  20170202135741  11211.0   
268611      275906   7411421    3750905  20170202135741  11211.0   
268612      275907  13780562   80910614  20170202135741  10314.0   
268613      275908  16660811   86973566  20170202135741  10460.0   
268614      275909  16998560   52002396  20170202135741  11215.0   
268615      275910  16781601   74633496  20170202135741  10453.0   
268616      275911  17016232   89415178  20170202135741  10038.0   
268617      275912  15476538    8832803  20170202135741   7087.0   
268618      275913   7843683   41330404  20170202135741  11003.0   
268619      275914  14521712   42088874  20170202135741  11004.0   
268620      275915    198471     968746  20170202135741  11234.0   
268621      275916  16824252   36728751  20170202135741  11102.0   
268622      275917   9773236   36274470  20170202135741  10021.0   
268623      275918  16976045    7264605  20170202135741  11226.0   
268624      275919  16627548    2300134  20170202135741  10026.0   
268625      275920  16925676  113061733  20170202135741  11234.0   
268626      275921   9915662   22976163  20170202135741  11232.0   
268627      275922  16714100   23716070  20170202135741  11225.0   
268628      275923  16642433    4224077  20170202135741  11215.0   
268629      275924  12089061   64777265  20170202135741  11694.0   
268630      275925  16604032   19108497  20170202135741  10029.0   
268631      275926  13555240   21011352  20170202135741  10019.0   
268632      275927  16519736   93723385  20170202135741  11234.0

In [48]:
def LRfindAveragePrice(location):
    return (df[(df.neighbourhood_cleansed == location)])

area = LRfindAveragePrice('woodside')
df = area
df.head()

Unnamed: 0      id  host_id       scrape_id  zipcode  \
713          766  270231  1366310  20181206022948  11377.0   
1196        1275  519310  1366310  20181206022948  11377.0   
1562        1655  704838  3621183  20181206022948  11377.0   
1609        1702  714028  3621183  20181206022948  11377.0   
1610        1703  714049  3621183  20181206022948  11377.0   

     neighbourhood_cleansed  property_type  room_type  accommodates  bedrooms  \
713                woodside              1       1.01             2       1.0   
1196               woodside              1       1.01             2       1.0   
1562               woodside              1       1.00             6       2.0   
1609               woodside              1       1.00             6       1.0   
1610               woodside              1       1.00             7       2.0   

      beds  bed_type  price  number_of_reviews  review_scores_rating  \
713    2.0       1.0   85.0                256                  96.0   
1196   1.0       1.0   75.0                238                  95.0   
1562   6.0       1.0  120.0                 48                  96.0   
1609   6.0       1.0  120.0                 44                  96.0   
1610   7.0       1.0  120.0                 43                  90.0   

      availability_30  minimum_nights  bathrooms  host_is_superhost  \
713                12               2        1.0                0.0   
1196               14               2        1.0                0.0   
1562               13               3        1.0                0.0   
1609                8               3        1.0                0.0   
1610               13               3        1.0                0.0   

      host_response_rate  
713                100.0  
1196               100.0  
1562                 0.0  
1609                 0.0  
1610                 0.0

# Load SVR 

In [49]:
from sklearn.svm import SVR
svr_lin = SVR(kernel='linear', C=100, gamma=0.1, epsilon=.1)

In [50]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(df[['accommodates', 'beds', 'bedrooms', 'bathrooms', 'bed_type','property_type', 'number_of_reviews', 'review_scores_rating']],
    df['price'], test_size = 0.30, random_state=42)

In [51]:
svr_lin.fit(xtrain,ytrain)
lin_pred=svr_lin.predict(xtest)
print(svr_lin.score(xtest,ytest))

0.39446899816358905


In [52]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(svr_linear, df[['accommodates', 'beds', 'bedrooms', 'bathrooms']], df['price'], cv=5)
scores

array([0.39746427, 0.55741593, 0.30494389, 0.5495589 , 0.56808446])

In [53]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.48 (+/- 0.21)


In [54]:
svr_linear.predict([[2, 1, 1, 2, 1, 1, 0, 98]])

array([58.1579169])

# RBF

In [92]:
svr_rbf.fit(xtrain,ytrain)
rbf_pred=svr_rbf.predict(xtest)
print(svr_rbf.score(xtest,ytest))

0.8233834336989783


In [94]:
svr_rbf.predict([[2, 1, 1, 1, 1, 1, 0, 70]])

array([80.32551175])

# Poly

In [ ]:
svr_poly.fit(xtrain,ytrain)
poly_pred=svr_poly.predict(xtest)
print(svr_poly.score(xtest,ytest))

In [ ]:
svr_linear.coef_

In [ ]:
svr_poly.predict([[2, 1, 1, 1, 1, 1]])

In [ ]:
df_predictors = df[['accommodates', 'availability_30', 'minimum_nights', 'number_of_reviews', 'room_type']]
df_target_value = df[['price']]

In [ ]:
import statsmodels.api as sm

df_predictors = sm.add_constant(df_predictors)
est = sm.OLS(df_target_value, 
            df_predictors).fit()
print(est.summary())